# Generated by Django 4.2.21 on 2025-05-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_comment_updated_at_thread_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='thread_covers/'),
        ),
    ]
